# Used by GitHub Pages. Sync changes except for the theme between this file and
# _config.local.yml.
remote_theme: mmistakes/minimal-mistakes
title: Creative Coding Lab
logo: /assets/images/cclab-logo-transparent.png

exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
