# Used for local development. Sync changes except for the theme between this
# file and _config.yml.
theme: minimal-mistakes-jekyll
title: Creative Coding Lab
logo: /assets/images/cclab-logo-transparent.png

exclude:
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - Gemfile
  - Gemfile.lock
